apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-inference
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-inference
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-inference
    spec:
      initContainers:
      - name: model-downloader
        image: ollama/ollama:latest
        command:
        - /bin/sh
        - -c
        - |
          ollama serve &
          sleep 10
          ollama pull {{ .Values.inference.model }}
          pkill ollama
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "8Gi"
            cpu: "2"
      containers:
        - name: {{ .Values.name }}-inference
          image: ollama/ollama:latest
          command:
          - /bin/sh
          - -c
          - |
            ollama serve
          ports:
          - containerPort: {{ .Values.inference.port }}
          env:
            - name: OLLAMA_HOST
              value: 0.0.0.0
          resources:
            requests:
              memory: "8Gi"
              cpu: "2"
              nvidia.com/gpu: 1
            limits:
              memory: "16Gi"
              cpu: "4"
              nvidia.com/gpu: 1
          volumeMounts:
          - name: ollama-data
            mountPath: /root/.ollama
          readinessProbe:
            httpGet:
              path: /
              port: 11434
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 11434
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi